import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Code Nest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="light"  enableSystem={true}>
          <Toaster />
          {children}
          <NextTopLoader color="#ff5e00" height={3} crawl crawlSpeed={200} showSpinner={false} easing="ease" />
        </ThemeProvider>

      </body>
    </html>
  );
}
