import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/navBar/navBar";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
          <main className="grid grid-cols-[1fr_4fr_1fr] grid-rows-[1fr_5fr]">
            <NavBar/>

            <main>
              {children}
            </main>

          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
