import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/navBar/navBar";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
          <NavBar/>

          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
