export const tags = [
  // 🔹 Linguagens de programação
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Go",
  "Rust",
  "PHP",
  "Ruby",
  "Kotlin",
  "Swift",
  "Dart",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "SASS",
  "LESS",
  
  // 🔹 Frameworks e bibliotecas front-end
  "React",
  "Next.js",
  "Gatsby",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "SvelteKit",
  "React Native",
  "Expo",
  
  // 🔹 Frameworks e bibliotecas back-end
  "Node.js",
  "Express",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "ASP.NET Core",
  
  // 🔹 Estilização / UI
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "Ant Design",
  "Bulma",
  
  // 🔹 Banco de dados
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "SQLite",
  "Firebase",
  "Firestore",
  "DynamoDB",
  
  // 🔹 DevOps / Infraestrutura
  "Docker",
  "Kubernetes",
  "Vercel",
  "Netlify",
  "AWS",
  "GCP",
  "Azure",
  "Serverless",
  
  // 🔹 Testes e qualidade
  "Jest",
  "Vitest",
  "Cypress",
  "Playwright",
  "React Testing Library",
  "Unit Test",
  "Integration Test",
  "End-to-End Test",
  
  // 🔹 Autenticação e segurança
  "JWT",
  "OAuth",
  "OpenID Connect",
  "NextAuth",
  "Passport.js",
  "bcrypt",
  "Argon2",
  
  // 🔹 Dev práticas / Arquitetura
  "Clean Code",
  "Refactoring",
  "TDD",
  "BDD",
  "SOLID",
  "DDD",
  "MVC",
  "MVVM",
  "Design Patterns",
  
  // 🔹 Ferramentas / utilitários
  "GraphQL",
  "REST API",
  "Apollo",
  "Prisma",
  "TypeGraphQL",
  "SWR",
  "React Query",
  "Redux",
  "Zustand",
  "Recoil",
  "RxJS",
  "Formik",
  "React Hook Form",
  
  // 🔹 Outras boas práticas
  "Performance",
  "Accessibility",
  "SEO",
  "Internationalization",
  "i18n",
  "Localization",
  "Code Review",
  "Pair Programming",
  "Microservices",
  "Clean Architecture"
];
